docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Intro: intro.md
    - Reference:
        - "Random Number Generation": rand.md
        - "Big Integers": big-integer.md
        - Migration: migration.md
site_name: laminas-math (Abandoned)
site_description: Create cryptographically secure pseudo-random numbers, and manage big integers
repo_url: 'https://github.com/laminas/laminas-math'
extra:
    project: Components
